name: libertymodel
description: liberty package for models.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.4
  ntp: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
